# Generated by Django 2.2.2 on 2019-06-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190618_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_jupyter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='show_in_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.TextField(blank=True),
        ),
    ]
