# Generated by Django 2.2.2 on 2019-07-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_disp_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['disp_order']},
        ),
    ]
