# Generated by Django 2.2.2 on 2019-06-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190626_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='images',
            field=models.ImageField(default='none', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
