# Generated by Django 2.2.2 on 2019-06-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_projects_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
