# Generated by Django 2.2.2 on 2019-06-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_projects_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='website/static/website/projects/images'),
        ),
    ]
