# Generated by Django 2.2.2 on 2019-06-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190626_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='images',
        ),
    ]
