# Generated by Django 2.2.2 on 2019-06-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_projects_show_in_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='abstract',
            field=models.TextField(blank=True),
        ),
    ]
