# Generated by Django 2.2.2 on 2019-06-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20190627_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='has_jupyter',
            field=models.BooleanField(default=False),
        ),
    ]
