# Generated by Django 2.2.2 on 2019-07-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_projects_has_jupyter'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='disp_order',
            field=models.IntegerField(blank=True, default=1000000),
        ),
    ]
