# Generated by Django 2.2.2 on 2019-07-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_projects_disp_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['disp_order'], 'verbose_name_plural': 'Projects'},
        ),
    ]
