# Generated by Django 2.2.2 on 2019-07-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20190701_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='part1_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='part2_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='part3_content',
            field=models.TextField(blank=True),
        ),
    ]
