# Generated by Django 2.2.2 on 2019-07-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20190715_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='part10_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='part1_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='part2_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='part3_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='part4_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='part5_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='part6_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='part7_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='part8_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='part9_link',
            field=models.URLField(blank=True),
        ),
    ]
