# Generated by Django 2.2.2 on 2019-07-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20190715_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='part10_link',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='part2_link',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='part3_link',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='part4_link',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='part5_link',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='part6_link',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='part7_link',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='part8_link',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='part9_link',
        ),
        migrations.AlterField(
            model_name='projects',
            name='part1_link',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
