# Generated by Django 2.2.2 on 2019-07-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20190715_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='part10_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part2_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part3_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part4_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part5_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part6_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part7_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part8_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part9_link',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
