# Generated by Django 2.2.2 on 2019-07-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20190715_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='links',
        ),
        migrations.AddField(
            model_name='projects',
            name='part10_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part10_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part1_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part1_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part2_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part2_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part3_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part3_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part4_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part4_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part5_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part5_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part6_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part6_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part7_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part7_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part8_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part8_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part9_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='part9_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
